# Generated by Django 5.0.6 on 2024-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_studenttype_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
