# Generated by Django 5.0.6 on 2024-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='image/icon_default.jpg', upload_to='', verbose_name='プロフィールの画像'),
        ),
    ]
